version: "3.9"

# used for specific settings you have outside of your docker config
# ex: proxies to external servers, storage configuration...
# remove this block entirely if not needed (Only used for Docker Swarm)
configs:
  caddy-basic-content:
    file: ./Caddyfile
    labels:
      caddy:

services:

  caddy_server:
    image: harbor.xxx.com/library/caddy-docker-proxy-alidns:2.8.4
    ports:
      - 8080:80
      - 8443:443
    networks:
      - caddy_controller
      - caddy
    environment:
      - CADDY_DOCKER_MODE=server
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
      - EMAIL=xxx@example.com  # Email for ACME registration and notifications
    volumes:
      # this volume is needed to keep the certificates
      # otherwise, new ones will be re-issued upon restart
      - caddy_data:/data
    configs:
      - source: caddy_dns_config
        target: /etc/caddy/Caddyfile
    deploy:
      replicas: 3
      labels:
        caddy_controlled_server:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  caddy_controller:
    image: harbor.xxx.com/library/caddy-docker-proxy-alidns:2.8.4
    networks:
      - caddy_controller
      - caddy
    environment:
      - CADDY_DOCKER_MODE=controller
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels: # Global options
        caddy.email: xxx@example.com
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  # Proxy to service
  whoami0:
    image: traefik/whoami
    networks:
      - caddy
    environment:
      - ALIDNS_ACCESS_KEY_ID=xxx  # AliDNS access key
      - ALIYUN_ACCESS_KEY_SECRET=xxx  # AliDNS secret key
    deploy:
      labels:
        caddy: whoami0.example.com
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls.protocols: "tls1.3" #### This is optional. Default it is tls1.2
        # remove the following line when you have verified your setup
        # Otherwise you risk being rate limited by let's encrypt
        caddy.tls.ca: https://acme-staging-v02.api.letsencrypt.org/directory
        #caddy.tls.ca: https://acme-v02.api.letsencrypt.org/directory
        caddy.tls.dns: "alidns"
        # 生产环境替换为字符串形式
        caddy.tls.dns.access_key_id: "{env.ALIDNS_ACCESS_KEY_ID}"
        caddy.tls.dns.access_key_secret: "{env.ALIDNS_SECRET_ACCESS_KEY}"

networks:
  caddy:
    driver: overlay
  caddy_controller:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "10.200.200.0/24"

volumes:
  caddy_data: {}